### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by ShaobinChen-AH** [YJiangcm/DCPCSE#1]
Hi! when I reproduced your results by running ''sh run_unsup_example.sh", I got the following error:

AttributeError: module 'senteval' has no attribute 'engine'.

And I did not find any exited solutions using Google. 
How can I solve this problem? Could you give me some advice? Thanks a lot.

**Comment by YJiangcm** [comment]
Thanks for pointing out the bug! The reason is that I forgot to upload the "__init__.py" file into the Senteval/senteval/ folder. I have added the missing file. Now the code should work well.
