### ISSUE TITLE
Models on Huggingface Hub

### ISSUE THREAD

**Issue by regstuff** [YJiangcm/DCPCSE#10]
Hi,
Was just testing out this repo and the results are quite good. Surprised this repo hasn't gotten more publicity.
Is there any chance of uploading the two models to Huggingface? Would make it easier to use in applications.

Thanks

**Comment by YJiangcm** [comment]
Thanks for your kind advice. The models have been uploaded to Huggingface (https://huggingface.co/YuxinJiang). I hope this helps you :)
