### ISSUE TITLE
Unsupervised Model Checkpoints

### ISSUE THREAD

**Issue by velocityCavalry** [YJiangcm/DCPCSE#3]
Hello,

Nice work to advance the SOTA! I was wondering whether you have plans in releasing the unsupervised model's checkpoint. 

Thanks!

**Comment by YJiangcm** [comment]
Hi, 

Sorry for the late reply. I have released the unsupervised BERT-base checkpoint, you can download it from the link https://drive.google.com/drive/folders/1OcgJ-7gU_N7J7x5ezrigFLlTU8h7Uvjx.
